// src/Web/ClientApp/src/components/Onboarding.jsx
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { OnboardingClient, SaveUserOnboardingCommand } from '../web-api-client';
import { useAuth } from './api-authorization/AuthContext';
import { Profile } from './shared/profile';


export function Onboarding() {
  return (
    <Profile heading="Set Up Your Profile" subTitle="Enter your starting weights and preferences to begin your program." />
     
  );
}

// src/Web/ClientApp/pages/onboarding.vue
<script setup lang="ts">
import { MiddlewareList, MiddlewareName } from '~/lib/middlewareList';

const list = new MiddlewareList();
definePageMeta({ middleware: list.getStringValueForEmum(MiddlewareName.Auth)})
</script>

<template>
  <SharedProfile
    heading="Set Up Your Profile"
    sub-title="Enter your starting weights and preferences to begin your program."
  />
</template>
